# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - stackoverflowtagger

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://stackoverflowtaggerimage.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_3dea4c21771b44b0b768c22aef7d6145 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_21a605a6f3764101a7f178969960daef }}

    
    - name: Build Docker image
      run: docker build -t my-app .

    - name: Run PyTest tests
      run: |
        docker run my-app pytest

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: stackoverflowtaggerimage.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3dea4c21771b44b0b768c22aef7d6145 }}/stackoverflowtaggerimage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'stackoverflowtagger'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7a49d14275ec4a28be8ec3082f47746b }}
        images: 'stackoverflowtaggerimage.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3dea4c21771b44b0b768c22aef7d6145 }}/stackoverflowtaggerimage:${{ github.sha }}'